FROM rocker/shiny:4.0.5

RUN apt-get update
RUN apt-get install -y libcurl4-gnutls-dev \
   libssl-dev \
   libxml2-dev \
   nano
   



RUN R -q -e "install.packages('plotly',repos='http://cran.rstudio.com/', version='4.9.3')" && \
    R -q -e "install.packages('deSolve',repos='http://cran.rstudio.com/', verion='1.28')" && \
    R -q -e "install.packages('tidyverse',repos='http://cran.rstudio.com/', version='1.3.1')" && \
    R -q -e "install.packages('dbplyr',repos='http://cran.rstudio.com/', version='2.1.1')" && \
    R -q -e "install.packages('pdfCluster',repos='http://cran.rstudio.com/' )" && \
    R -q -e "install.packages('shinythemes',repos='http://cran.rstudio.com/', version='1.2.0')" && \
    R -q -e "install.packages('shinycssloaders',repos='http://cran.rstudio.com/', version='1.0.0')" && \
    R -q -e "install.packages('EpiModel',repos='http://cran.rstudio.com/', version='2.0.3')" && \
    R -q -e "install.packages('survival',repos='http://cran.rstudio.com/', version='3.2-7')" && \
    R -q -e "install.packages('viridis',repos='http://cran.rstudio.com/', version='0.6.0')" && \
    R -q -e "install.packages('devtools',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('DT',repos='http://cran.rstudio.com/')"
    
RUN R -q -e "install.packages('devtools')" && \ 
    R -q -e "library('devtools'); install_github('trestletech/shinyStore')" 
    
RUN R -q -e "install.packages('EasyABC')"

    
COPY ./source/shiny-server.conf /etc/shiny-server/shiny-server.conf
ADD ./source /srv/shiny-server/shiny

# run app
#CMD ["/usr/bin/shiny-server"]